# Generated by Django 5.0.8 on 2024-08-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.IntegerField()),
                ('movieId', models.IntegerField()),
                ('relevance', models.FloatField()),
            ],
            options={
                'db_table': 'genome_scores',
            },
        ),
        migrations.CreateModel(
            name='GenomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genome_tags',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField()),
                ('imdbId', models.CharField(max_length=100)),
                ('tmdbId', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('userId', models.IntegerField()),
                ('movieId', models.IntegerField()),
                ('timestamp', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
