# Generated by Django 5.0.8 on 2024-08-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_genomescore_genometag_link_movie_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie',
            new_name='movieId',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='userId',
        ),
    ]
