# Generated by Django 5.0.8 on 2024-08-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_alter_movie_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Processing', max_length=50)),
                ('success_count', models.IntegerField(blank=True, null=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
                ('processing_duration', models.DurationField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='processchunk',
            name='process',
        ),
        migrations.AddField(
            model_name='processchunk',
            name='uploaded_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='processes.uploadedfile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
