# Generated by Django 5.0.8 on 2024-08-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_rename_movie_rating_movieid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomescore',
            name='movieId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genomescore',
            name='relevance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='genomescore',
            name='tagId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genometag',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='genometag',
            name='tagId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='imdbId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='tmdbId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movieId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='timestamp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='movieId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='timestamp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
