# Generated by Django 5.0.8 on 2024-08-12 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_alter_uploadedfile_error_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomescore',
            name='movieid',
            field=models.ForeignKey(db_column='movieid', on_delete=django.db.models.deletion.CASCADE, to='processes.movie'),
        ),
        migrations.AlterField(
            model_name='link',
            name='movieid',
            field=models.ForeignKey(db_column='movieid', on_delete=django.db.models.deletion.CASCADE, to='processes.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movieid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='processes.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='movieid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='processes.movie'),
            preserve_default=False,
        ),
    ]
