# Generated by Django 5.0.8 on 2024-08-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_rename_id_movie_movieid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenomeScore',
        ),
        migrations.DeleteModel(
            name='GenomeTag',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
