# Generated by Django 5.0.8 on 2024-08-12 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_alter_genomescore_movieid_alter_link_movieid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movieid',
            field=models.ForeignKey(db_column='movieid', on_delete=django.db.models.deletion.CASCADE, to='processes.movie'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='movieid',
            field=models.ForeignKey(db_column='movieid', on_delete=django.db.models.deletion.CASCADE, to='processes.movie'),
        ),
    ]
