# Generated by Django 5.0.8 on 2024-08-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0006_delete_genomescore_delete_genometag_delete_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField(null=True)),
                ('tagId', models.IntegerField(null=True)),
                ('relevance', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'genome_scores',
            },
        ),
        migrations.CreateModel(
            name='GenomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.IntegerField(null=True)),
                ('tag', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'genome_tags',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField()),
                ('imdbId', models.CharField(max_length=100, null=True)),
                ('tmdbId', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('genres', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(null=True)),
                ('movieId', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('timestamp', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(null=True)),
                ('movieId', models.IntegerField(null=True)),
                ('tag', models.CharField(max_length=255, null=True)),
                ('timestamp', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
