# Generated by Django 5.0.8 on 2024-08-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movieId',
            new_name='movieid',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='userId',
            new_name='userid',
        ),
    ]
