# Generated by Django 5.0.8 on 2024-08-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_movie_average_rating_movie_num_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='num_votes',
        ),
    ]
