# Generated by Django 5.0.8 on 2024-08-12 17:13

from django.db import migrations
from django.db import connection

def refresh_movie_ratings_summary(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE MATERIALIZED VIEW IF NOT EXISTS movie_ratings_summary AS
            SELECT
                m.movieid,
                m.title,
                m.genres,
                AVG(r.rating) as average_rating,
                COUNT(r.rating) as num_votes,
                CASE
                    WHEN regexp_replace(m.title, '\\D*(\\d{4})\\D*', '\\1', 'g') ~ '^\d{4}$'
                    THEN CAST(regexp_replace(m.title, '\\D*(\\d{4})\\D*', '\\1', 'g') AS INTEGER)
                    ELSE NULL
                END as release_year
            FROM
                movies m
            LEFT JOIN
                ratings r ON m.movieid = r.movieid
            GROUP BY
                m.movieid, m.title, m.genres
        """)
        cursor.execute("REFRESH MATERIALIZED VIEW movie_ratings_summary;")



class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_remove_movie_average_rating_remove_movie_num_votes'),
    ]

    operations = [
        migrations.RunPython(refresh_movie_ratings_summary),
    ]  

  