# Generated by Django 5.0.8 on 2024-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_rename_movieid_rating_movieid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
