# Generated by Django 5.0.8 on 2024-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_create_movie_ratings_summary_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRatingsSummary',
            fields=[
                ('movieid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('average_rating', models.FloatField()),
                ('num_votes', models.IntegerField()),
                ('release_year', models.IntegerField()),
            ],
            options={
                'db_table': 'movie_ratings_summary',
                'managed': False,
            },
        ),
    ]
