# Generated by Django 5.0.8 on 2024-08-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genomescore',
            old_name='movieId',
            new_name='movieid',
        ),
        migrations.RenameField(
            model_name='genomescore',
            old_name='tagId',
            new_name='tagid',
        ),
        migrations.RenameField(
            model_name='genometag',
            old_name='tagId',
            new_name='tagid',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='imdbId',
            new_name='imdbid',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='movieId',
            new_name='movieid',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='tmdbId',
            new_name='tmdbid',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movieId',
            new_name='movieid',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='movieId',
            new_name='movieid',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='userId',
            new_name='userid',
        ),
    ]
